# -*- coding: utf-8 -*-
"""Mision_uni_1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aijBh4kl_g2xD7lrh9cNNIlxKD64OghI

## 1
# Conversor de Sistemas Numéricos (Binario, Decimal y Hexadecimal)

Este programa realiza conversiones entre diferentes sistemas de numeración (Base 2, Base 10 y Base 16) aplicando algoritmos matemáticos propios y modularización mediante funciones en Python.
"""

# Desarrolle su ejercicio aquí.

menu = [
    "Binario a Decimal",
    "Hexadecimal a Decimal",
    "Decimal a Binario",
    "Decimal a Hexadecimal",
    "Binario a Hexadecimal",
    "Hexadecimal a Binario"
]

guia = "0123456789ABCDEF0123456789abcdef"

# Mostrar menú
def mostrar_menu():
    print("\nBienvenido a la calculadora de conversiones")
    print("Estas son las conversiones disponibles:\n")
    for i in range(len(menu)):
        print(f"{i}. {menu[i]}")

# Pedir el índice de la conversión
def pedir_indice():
    while True:
        entrada = input("\nIngrese el índice de la conversión: ")

        if entrada.isdigit() and 0 <= int(entrada) < len(menu):
            return int(entrada)
        print(f"Índice inválido. Debe ser un número entre 0 y {len(menu) - 1}.")

# Pedir el valor a convertir (valida que no esté vacío)
def pedir_valor():
    while True:
        valor = input("Ingrese el valor que desea convertir: ").strip()
        if valor != "":
            return valor
        print("Error: Debe ingresar al menos un carácter.")

# Primera conversión: Binario a decimal
def binario_a_decimal(valor):
    suma = 0
    potencia = 0
    largo = len(valor)
    for i in range(largo):
        caracter = valor[largo - 1 - i]
        digito = int(caracter)
        suma = suma + (digito * (2 ** potencia))
        potencia = potencia + 1

    print("El resultado es:", suma)

# Segunda conversión: Hexadecimal a decimal
def hexadecimal_a_decimal(valor):
    suma = 0
    potencia = 0
    largo = len(valor)
    for i in range(largo):
        caracter = valor[largo - 1 - i]
        digito = guia.index(caracter)

        if digito > 15:
            digito = digito - 16

        suma = suma + (digito * (16 ** potencia))
        potencia = potencia + 1

    print("El resultado es:", suma)

# Tercera conversión: Decimal a binario
def decimal_a_binario(valor):
    valor = int(valor)
    if valor == 0:
        resultado = "0"
    else:
        resultado = ""
        while valor > 0:
            residuo = valor % 2
            resultado = str(residuo) + resultado
            valor = valor // 2

    print("El resultado es:", resultado)

# Cuarta conversión: Decimal a hexadecimal
def decimal_a_hexadecimal(valor):
    valor = int(valor)  # ARREGLADO: Se convierte la cadena a entero
    if valor == 0:
        resultado = "0"
    else:
        resultado = ""
        while valor > 0:
            residuo = valor % 16
            letra = guia[residuo]
            resultado = letra + resultado
            valor = valor // 16

    print("El resultado es:", resultado)

# Quinta conversión: Binario a hexadecimal
def binario_a_hexadecimal(valor):
    suma_temporal = 0
    potencia = 0
    largo = len(valor)
    for i in range(largo):
        caracter = valor[largo - 1 - i]
        digito = int(caracter)
        suma_temporal = suma_temporal + (digito * (2 ** potencia))
        potencia = potencia + 1

    if suma_temporal == 0:
        resultado = "0"
    else:
        resultado = ""
        while suma_temporal > 0:
            residuo = suma_temporal % 16
            letra = guia[residuo]
            resultado = letra + resultado
            suma_temporal = suma_temporal // 16

    print("El resultado es:", resultado)

# Sexta conversión: Hexadecimal a Binario
def hexadecimal_a_binario(valor):
    suma_temporal = 0
    potencia = 0
    largo = len(valor)
    for i in range(largo):
        caracter = valor[largo - 1 - i]

        # ARREGLADO: Se usa 'digito' para no sobrescribir el texto 'valor'
        digito = guia.index(caracter)
        if digito > 15:
            digito = digito - 16
        suma_temporal = suma_temporal + (digito * (16 ** potencia))
        potencia = potencia + 1

    if suma_temporal == 0:
        resultado = "0"
    else:
        resultado = ""
        while suma_temporal > 0:
            residuo = suma_temporal % 2
            resultado = str(residuo) + resultado
            suma_temporal = suma_temporal // 2

    print("El resultado es:", resultado)

### Filtro if, elif y else
mostrar_menu()
indice = pedir_indice()
valor = pedir_valor()

if indice == 0:
    binario_a_decimal(valor)
elif indice == 1:
    hexadecimal_a_decimal(valor)
elif indice == 2:
    decimal_a_binario(valor)
elif indice == 3:
    decimal_a_hexadecimal(valor)
elif indice == 4:
    binario_a_hexadecimal(valor)
elif indice == 5:
    hexadecimal_a_binario(valor)
else:
    print("Índice inválido")

"""##  2
# Cálculo de Distancia Euclidiana entre Puntos Cartesianos

Este programa calcula la distancia geométrica en el plano bidimensional entre dos puntos $P_1(x_1, y_1)$ y $P_2(x_2, y_2)$ aplicando la fórmula euclidiana.  
"""

import math

# 1. Función requerida por el ejercicio
def calcular_distancia():
    while True:
        try:
            x1 = float(input("  Coordenada x1: "))
            y1 = float(input("  Coordenada y1: "))
            x2 = float(input("  Coordenada x2: "))
            y2 = float(input("  Coordenada y2: "))
            break
        except ValueError:
            print("  [Error] Por favor, ingrese solo números.\n")

    # Cálculo y respuesta formateada
    distancia = math.sqrt(((x2 - x1) ** 2) + ((y2 - y1) ** 2))
    print(f"  La distancia resultante es: {distancia:,.2f}")



# Pedir la cantidad de veces que se calculará la distancia
while True:
    try:
        cantidad = int(input("¿Cuántas distancias desea calcular?: "))
        if cantidad > 0:
            break
        print("Ingrese un número mayor a 0.\n")
    except ValueError:
        print("Error: Ingrese un número entero válido.\n")

# Repetir la función la cantidad de veces solicitada
for i in range(1, cantidad + 1):
    print(f"\n--- Cálculo {i} de {cantidad} ---")
    calcular_distancia()

print("\n¡Proceso finalizado!")



"""## 3

# Calculadora de Desempeño Académico y Promedio Ponderado

Este programa es una herramienta de gestión académica diseñada para calcular la nota final ponderada de un curso con un número dinámico de actividades y esquemas de evaluación variables.
"""

# Desarrolle su ejercicio aquí


def pedir_cantidad():
    cantidad = int(input("Ingrese la cantidad de tareas que tiene la asignatura: "))
    return cantidad


def recopilar_datos(cantidad_tareas):
    nombres = []
    ponderaciones = []
    notas = []

    for i in range(cantidad_tareas):
        print(f"\n--- Datos de la tarea {i+1} ---")
        nombres.append(input("Nombre de la tarea: "))
        ponderaciones.append(float(input("Ponderación de la tarea: ")))
        notas.append(float(input("Calificación de la tarea: ")))


    return nombres, ponderaciones, notas


def calcular_final(lista_ponderaciones, lista_notas):
    suma_global = 0
    cantidad = len(lista_notas)

    for i in range(cantidad):
        suma_global += lista_ponderaciones[i] * lista_notas[i]

    suma_peso = sum(lista_ponderaciones)

    if suma_peso > 0:
        return suma_global / suma_peso
    else:
        return 0


def main():

    cantidad = pedir_cantidad()


    nombres, pesos, calificaciones = recopilar_datos(cantidad)


    nota_final = calcular_final(pesos, calificaciones)


    print(f"\nLa calificación final del curso es: {nota_final:.2f}")


main()

"""# **4.**
 ## Conversor de Unidades Interactivo con Vectores y Funciones


Este programa es un sistema interactivo de conversión de unidades de medida construido en Python bajo el paradigma de programación modular.
"""

# Desarrolle su ejercicio aquí.
trm = 3126.08


factores = [
    1000,       # 0 -> Kilómetro a metro
    0.01,       # 1 -> Centímetro a metro
    0.62,       # 2 -> Kilómetro por hora a millas por hora
    20,         # 3 -> Nota en Educatic a nota en Canvas
    0.05,       # 4 -> Nota en Canvas a nota en Educatic
    1,          # 5 -> Mililitro a centímetro cúbico
    trm,        # 6 -> Dólar (USA) a peso colombiano
    1 / trm,    # 7 -> Peso colombiano a dólar (USA)
    0.45,       # 8 -> Libra a kilogramo
    17987539.67 # 9 -> Minuto luz a kilómetro
]


conversiones = [
    "Kilómetro a metro",
    "Centímetro a metro",
    "Kilómetro por hora a millas por hora",
    "Nota en Educatic a nota en Canvas",
    "Nota en Canvas a nota en Educatic",
    "Mililitro a centímetro cúbico",
    "Dólar (USA) a peso colombiano",
    "Peso colombiano a dólar (USA)",
    "Libra a kilogramo",
    "Minuto luz a kilómetro"
]

def mostrar_menu():

    print("\nBienvenido a la calculadora de conversiones")
    print("Estas son las conversiones disponibles:\n")

    for i in range(len(conversiones)):
        print(f"{i}. {conversiones[i]}")


def pedir_indice():
    while True:
        entrada = input("\nIngrese el número de la conversión: ")

        if entrada.isdigit() and 0 <= int(entrada) < len(conversiones):
            return int(entrada)

        print("Índice inválido. Debe ser un número entre 0 y 9.")


def pedir_valor():
    while True:
        try:
            valor = float(input("Ingrese el valor que desea convertir: "))
            return valor
        except ValueError:
            print("Valor inválido. Debe ingresar un número.")


def convertir(valor, indice):
    return valor * factores[indice]



def desea_continuar():
    while True:
        respuesta = input("\n¿Desea realizar otra conversión? (si/no): ").strip().lower()

        if respuesta in ("si", "sí", "s"):
            return True
        if respuesta in ("no", "n"):
            return False

        print("Respuesta inválida. Escriba 'si' o 'no'.")


def main():
    continuar = True

    while continuar:
        mostrar_menu()
        indice = pedir_indice()
        valor = pedir_valor()
        resultado = convertir(valor, indice)
        print(f"\nEl resultado de la conversión es: {resultado:g}")

        continuar = desea_continuar()

    print("\nGracias por usar la calculadora")


main()